name: Test

on: push

jobs:
  test:
    runs-on: [aio-small-org-runner-folloze]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx jest --verbose
